### ISSUE TITLE
Description of csv

### ISSUE THREAD

**Issue by mgraauw** [lhncbc/ucum-lhc#10]
The demo page allows uploading of CSV. It would be a nice addition to state the required CSV format (since CSV is not a formal standard, and quite some variants are used in de practice - standard Excel to CSV export did not work for me). 
I got it to work with:
- commas as delimiter (not semicolon)
- all fields double quoted ("ml", etc., not just ml, ...)
- \r\n line ends (Unix style \n did not work)
Maybe more formats are allowed, but the only way to find out what works now is by trial-and-error.

**Comment by plynchnlm** [comment]
Yes, good idea.  I'm sorry you had to figure it out by trial and error.

**Comment by plynchnlm** [comment]
This was done back in 2020, and I forgot to close this.
