### ISSUE TITLE
Development dependency in production dependencies

### ISSUE THREAD

**Issue by thurrox** [lhncbc/ucum-lhc#16]
Should the `grunt-extract-sourcemap` dependency be declared in the development dependencies? Got the following error from npm:

`npm WARN grunt-extract-sourcemap@0.1.19 requires a peer of grunt@>=0.4.0 but none is installed. You must install peer dependencies yourself.`

**Comment by plynchnlm** [comment]
Yes, it should.  Thanks for bringing this to our attention.  We will make that change.  In the meantime, you should be okay since it is just a warning.

**Comment by thurrox** [comment]
No problem, thank you for the fast reaction 👍

**Comment by plynchnlm** [comment]
This is fixed in 4.1.4.
