### ISSUE TITLE
Unit conversion does not work for 0

### ISSUE THREAD

**Issue by ivanovgp** [lhncbc/ucum-lhc#2]
convertUnitTo() does not support an input value of 0. Try 0m to km.

**Comment by plynchnlm** [comment]
Thanks for reporting this.  I can also see the problem on the demo at https://lhncbc.github.io/ucum-lhc/demo.html .  We'll take a look.

**Comment by plynchnlm** [comment]
A fix is under review along with some other changes-- hopefully coming soon.

**Comment by plynchnlm** [comment]
Thank you for your patience.  This should now be fixed in version 2.1.2.
