### ISSUE TITLE
Documentation - how to correctly reference using ucum-lhc

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [lhncbc/ucum-lhc#28]
Hi, can you please include into a documentation how to correctly reference when using ucum-lhc in another open source project? For example when LOINC and UCUM is used, their terms apply which is totally fine. But how to correctly reference this? 

Would it be sufficient to have a third party license file containing all license texts/terms-of-service from all references? So the following ones:
- https://github.com/lhncbc/ucum-lhc/blob/master/LICENSE.md
- https://loinc.org/kb/license/
- https://ucum.org/trac/wiki/license

Or would something else be required?
Thanks

**Comment by plynchnlm** [comment]
I think that would cover it.  Thanks for checking.
