### ISSUE TITLE
Q: Synonym data?

### ISSUE THREAD

**Issue by incansvl** [lhncbc/ucum-lhc#34]
To the best of my knowledge the UCUM data definition (ucum-essence.xml) doesn't include synonyms for unit codes, with the exception of a textual name/description and (sometimes) a "printSymbol".

So, where is the "synonym data" drawn from in this implementation to provide the _checkSynonyms()_ function? Is this supplemental data that's been added to the master UCUM file from another source?

**Comment by incansvl** [comment]
Thanks. So there is supplementary data in the package that is loaded in addition to the ucum-essence.xml file. I'd be interested to know where. I know I could trawl the source files but that would take a while I imagine.

**Comment by plynchnlm** [comment]
https://github.com/lhncbc/ucum-lhc/blob/master/data/ucum.csv
