### ISSUE TITLE
UCUM_LHC allows multiple prefixes that are invalid

### ISSUE THREAD

**Issue by andrey-hssc** [lhncbc/ucum-lhc#40]
The UCUM LHC demo interprets `mcg` as

`mcg (millicentigram) is a valid unit expression.`

This interpretation is based on multiple prefixes `m` and `c` combined with a single base unit `g`. Multiple prefixes are not allowed per UCUM section 4.2:

> The unit symbol to be combined with the prefix must not itself contain a prefix. Such a prefix-less unit symbol is called unit atom.

**Comment by plynchnlm** [comment]
Confirmed.  Thanks for the report.  Interestingly, it does not accept mmcg, nor mmJ.

**Comment by plynchnlm** [comment]
Fixed in version 4.1.7, but it is not yet on the demo site.

**Comment by plynchnlm** [comment]
The demo site at https://ucum.nlm.nih.gov/ucum-lhc/demo.html has been updated with fix (version 4.1.7).
