### ISSUE TITLE
Where to create a UcumLhcUtils object that contains those two functions?

### ISSUE THREAD

**Issue by linforestzhang** [lhncbc/ucum-lhc#44]
Where to create a UcumLhcUtils object that contains those two functions, from the server side?  
var ucum = require('@lhncbc/ucum-lhc'); 
var utils = ucum.UcumLhcUtils.getInstance();

Thanks!

Regards,
.. Lin

**Comment by plynchnlm** [comment]
I am not sure what you mean by "where".  You don't create UcumLhcUtils yourself, but you call getInstance() to get an instance of it, using the code you quoted.  If have the package installed via npm, you can just run "node" and those two lines should work to get you the instance.

**Comment by linforestzhang** [comment]
Thanks a lot, Paul!

**Comment by plynchnlm** [comment]
You are welcome!
