### ISSUE TITLE
Unexpected presence of "." in "sup" tags

### ISSUE THREAD

**Issue by alexandre-le-borgne** [lhncbc/ucum-lhc#48]
In file https://github.com/lhncbc/ucum-lhc/blob/master/browser-dist/ucum-lhc.js
Line 2

https://raw.githubusercontent.com/lhncbc/ucum-lhc/master/browser-dist/ucum-lhc.js

The vast majority of `<sup>` tags are correctly closed with `</sup>`, however some are closed with <.sup>

![Screenshot_20231127_153436](https://github.com/lhncbc/ucum-lhc/assets/10196942/fa213a58-bf7b-4b91-b760-510a2f90c0e6)

**Comment by plynchnlm** [comment]
Thanks for bringing this to our attention.  It does not seem to be an error in our data files, but in some code that is generating those strings.  We will fix this as soon as we can.

**Comment by jcy1225** [comment]
This issue is fixed with latest version.
