### ISSUE TITLE
Error when instantiating using ES6 import

### ISSUE THREAD

**Issue by josh-g3** [lhncbc/ucum-lhc#5]
I'm using Node & Babel, ES6 import is part of my team's coding style guide.

This works:

```js
const ucumlhc = require('@lhncbc/ucum-lhc');
const ucum = ucumlhc.UcumLhcUtils.getInstance();
```

While this does not:

```js
import ucumlhc from '@lhncbc/ucum-lhc';
const ucum = ucumlhc.UcumLhcUtils.getInstance();
```

The latter throws the following error:

```
TypeError: Cannot read property 'UcumLhcUtils' of undefined
```

Please advise and thank you in advance!

**Comment by josh-g3** [comment]
Node 9.8.0 and Babel 6.26.0

Here's how it looks transpiled:

```js
var _ucumLhc = require('@lhncbc/ucum-lhc');
var _ucumLhc2 = _interopRequireDefault(_ucumLhc);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var ucum = _ucumLhc2.default.UcumLhcUtils.getInstance();
```

**Comment by plynchnlm** [comment]
So, the source code for this library was itself written with ES6 modules and transpiled using Babel to the package you are requiring.  Line 3 (which defines the _interop... function) checks obj.__esModule, which is set to true in our code, presumably by Babel during the transpilation we did on our end.  So, _ucumLhc2 === ucumLhc.  I don't know why line 4 assumes and an ES6 module export object has a "default" property, but ours does not.  I guess it has something to do with trying to get the default export, but I haven't found anything that talks about a "default" property on that export (though I am new to ES6 modules myself).  Perhaps it is a bug in babel?

As a work-around, could you just as easily write:
```
import * as ucumlhc from '@lhncbc/ucum-lhc';
```
I tried that here, and Babel transpiled it into something different, which seems to work:

```
$ cat test3.js
import * as ucumLhc from "@lhncbc/ucum-lhc"; console.log(ucumLhc.UcumLhcUtils.getInstance());
$ node_modules/.bin/babel test3.js |node
UcumLhcUtils {
  uStrParser_: ....
}
```

**Comment by plynchnlm** [comment]
Glad that worked!
