### ISSUE TITLE
"m(/s)" passes validation and gives "1/s" as result

### ISSUE THREAD

**Issue by dalito** [lhncbc/ucum-lhc#50]
Entering `m(/s)` in the [web-validator](https://ucum.nlm.nih.gov/ucum-lhc/demo.html) gives: `m(/s) (1/[second - time]) is a valid unit expression.` The "meter" is lost. I would expect that this fails validation.

Another interesting edge case is `m.(/s)`. It passes validation and gives `m.(/s) (meter*[1/[second - time]]) is a valid unit expression.` - This should probably also fail at least according to

* [Syntax in BNF form](https://ucum.org/ucum#section-Syntax-Rules) in the specification
* [ucum-state-automaton](https://github.com/ucum-org/ucum/blob/main/assets/images/ucum-state-automaton.gif) figure
* [formal grammar](https://ucum.org/docs/formal-grammar) page

These formal grammars only allow "/" as unary operator at the beginning of a "main term" but not as unary operator of a "term". Interestingly, the [written specification](https://ucum.org/docs/formal-grammar) only says: *The division operator can be used as a binary and unary operator, i.e. a leading solidus will invert the unit that directly follows it.* - This is what your code does for `m.(/s)`.

**Comment by dalito** [comment]
A clarification that unary "/" may only be used at the beginning of the unit code has been added 2013 in https://github.com/ucum-org/ucum/commit/28961d6769380bba7b181dc5a78434ba0778959d (see file `ucum-source.xml`)- So unary "/" is really limited to the front.

**Comment by plynchnlm** [comment]
Thanks for reporting this.  I agree that m(/s) should be invalid, and that it's current description is incorrect.  I will go ahead and add that one to our internal list of issues.

You make a strong argument for also regarding m.(/s) as invalid, though I would like to wait to see some action on the ucum-org ticket you filed just to make sure, because the text's wording is ambiguous.

**Comment by jcy1225** [comment]
This issue is fixed with the latest version.
