### ISSUE TITLE
A potential typo in the Guidance for Ampere

### ISSUE THREAD

**Issue by linforestzhang** [lhncbc/ucum-lhc#51]
In ucum.csv, there might exist a typo in the Guidance for Ampere:
`unit of electric current equal to flow rate of electrons equal to **16.2415×10^18** elementary charges moving past a boundary in one second or 1 Coulomb/second`

Proposed correction:
`unit of electric current equal to flow rate of electrons equal to **6.2415×10^18** elementary charges moving past a boundary in one second or 1 Coulomb/second`

**Comment by plynchnlm** [comment]
This and the other two typos are now fixed in the demo app at (https://ucum.nlm.nih.gov/ucum-lhc/demo.html), but the fix for the library itself is still under review.  (Not that that the typo fixes need review, but some other issues arose with the build).

**Comment by jcy1225** [comment]
This is now fixed in version 5.0.3.
