### ISSUE TITLE
Unexpected results from conversion of unit expression (web service)

### ISSUE THREAD

**Issue by incansvl** [lhncbc/ucum-lhc#8]
Note: This issue specifically refers to the online web service

Given the query URL:

`https://ucum.nlm.nih.gov/ucum-service/v1/toBaseUnits/mmol/L`

The response is:
`<UCUMWebServiceResponse ServerDateTime="2018-11-26T16:11:55">
<WebServiceRequest>
http://ucum.nlm.nih.gov/ucum-service/v1/toBaseUnits/mmol/L
</WebServiceRequest>
<Response>
<SourceUnit>mmol/L</SourceUnit>
<ResultBaseUnits>mol.m-3</ResultBaseUnits>
<ResultQuantity>1.0</ResultQuantity>
<ResultBaseUnitsList>
<BaseUnit Name="mol" Exponent="1"/>
<BaseUnit Name="m" Exponent="-3"/>
</ResultBaseUnitsList>
</Response>
</UCUMWebServiceResponse>`

I believe the ResultQuantity should be 1000 (or 10^3) in this case, as 1mol/L == 1000mol/m^3

**Comment by plynchnlm** [comment]
Your URL is mmol/L, not mol/L, so I think the response is correct.

1 mmol/L = mmol/(0.1 m)^3 = 1000 mmol/m^3 = 1 mol/m^3

**Comment by incansvl** [comment]
You're right, I missed the conversion from mmol to mol. My mistake, thanks for the reply.
